### ISSUE TITLE
Migrate to GitLab

### ISSUE THREAD

**Issue by brlin-tw** [brlin-tw/brlin-tw.github.io#4]
I plan to migrate this project to GitLab while keeping this repo as a mirror.

[Previously blocked due to a GitLab problem](https://gitlab.com/gitlab-org/gitlab/-/issues/469228#note_2150118343), though.  For this project I'll migrate using alternative means.

## Subtasks

* [x] Create a GitLab project
* [x] Push code to GitLab
* [x] Setup repo mirroring from GitLab to GitHub
* [x] Migrate to Jekyll neutral site configuration
* [x] Setup GitLab Pages site

**Comment by brlin-tw** [comment]
Implemented: <https://brlin.gitlab.io/>
